# Generated by Django 3.1 on 2020-08-29 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companymanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.CharField(max_length=300),
        ),
    ]
